# Generated by Django 3.1 on 2021-06-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_contributorguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributorguide',
            name='stack',
        ),
    ]
