insert into public.work_taskcategorylist (id, active, selectable, name, expertise, parent_id)
values (1, false, false, 'Art & Creative', '{}', NULL),
       (2, false, false, '2D Animation', '{}', 1),
       (3, false, false, 'Acting', '{}', 1),
       (4, false, false, 'AR/VR Design', '{}', 1),
       (5, false, false, 'Art Direction', '{}', 1),
       (6, false, false, 'Audio Editing', '{}', 1),
       (7, false, false, 'Audio Production', '{}', 1),
       (8, false, false, 'Brand Design', '{}', 1),
       (9, false, false, 'Caricatures & Portraits', '{}', 1),
       (10, false, false, 'Cartoons & Comics', '{}', 1),
       (11, false, false, 'Creative Direction', '{}', 1),
       (12, false, false, 'Editorial Design', '{}', 1),
       (13, false, false, 'Game Art', '{}', 1),
       (14, false, false, 'Local Photography', '{}', 1),
       (15, false, false, 'Motion Graphics', '{}', 1),
       (16, false, false, 'Image Editing', '{}', 1),
       (17, false, false, 'Music Composition', '{}', 1),
       (18, false, false, 'Music Production', '{}', 1),
       (19, false, false, 'Musician', '{}', 1),
       (20, false, false, 'Packaging Design', '{}', 1),
       (21, false, false, 'Pattern Design', '{}', 1),
       (22, false, false, 'Presentation Design', '{}', 1),
       (23, false, false, 'Product & Industrial Design', '{}', 1),
       (24, false, false, 'Product Photography', '{}', 1),
       (25, false, false, 'Video Editing', '{}', 1),
       (26, false, false, 'Video Production', '{}', 1),
       (27, false, false, '3D Animation', '{}', 1),
       (28, false, false, 'Videography', '{}', 1),
       (29, false, false, 'Visual Effects', '{}', 1),
       (30, false, false, 'Customer Service & Support', '{}', NULL),
       (31, false, false, 'Customer Service', '{}', 30),
       (32, false, false, 'Tech Support', '{}', 30),
       (33, false, false, 'Data Science & Analytics', '{}', NULL),
       (34, false, false, 'Data Analytics', '{}', 33),
       (35, false, false, 'Data Engineering', '{}', 33),
       (36, false, false, 'Data Extraction', '{}', 33),
       (37, false, false, 'Data Mining', '{}', 33),
       (38, false, false, 'Data Processing', '{}', 33),
       (39, false, false, 'Data Visualization', '{}', 33),
       (40, false, false, 'Deep Learning', '{}', 33),
       (41, false, false, 'Experimentation & Testing', '{}', 33),
       (42, false, false, 'Knowledge Representation', '{}', 33),
       (43, false, false, 'Machine Learning', '{}', 33),
       (44, false, false, 'Engineering, Science & Building', '{}', NULL),
       (45, false, false, '3D Modelling & Rendering', '{}', 44),
       (46, false, false, 'Building Information Modelling', '{}', 44),
       (47, false, false, 'Mathematics', '{}', 44),
       (48, false, false, 'Sourcing & Procurement', '{}', 44),
       (49, false, false, 'General Support', '{}', NULL),
       (50, false, false, 'Accounting & Finance', '{}', 49),
       (51, false, false, 'Legal Support', '{}', 49),
       (52, false, false, 'Project Management', '{}', 49),
       (53, false, false, 'Agile Coach', '{}', 49),
       (54, true, false, 'Information Systems & Networking', '{}', NULL),
       (55, false, false, 'Business Applications Development', '{}', 54),
       (56, true, true, 'Cloud Engineering', '{}', 54),
       (57, false, false, 'Database Administration', '{}', 54),
       (58, true, true, 'DevOps Engineering', '{}', 54),
       (59, true, true, 'Information Security', '{}', 54),
       (60, false, false, 'IT Compliance', '{}', 54),
       (61, false, false, 'IT Support', '{}', 54),
       (62, false, false, 'Network Administration', '{}', 54),
       (63, false, false, 'Network Security', '{}', 54),
       (64, true, true, 'Solutions Architecture', '{}', 54),
       (65, false, false, 'Systems Administration', '{}', 54),
       (66, false, false, 'Systems Engineering', '{}', 54),
       (67, false, false, 'Marketing, Sales & Communications', '{}', NULL),
       (68, false, false, 'Brand Strategy', '{}', 67),
       (69, false, false, 'Campaign Management', '{}', 67),
       (70, false, false, 'Community Management', '{}', 67),
       (71, false, false, 'Content Strategy', '{}', 67),
       (72, false, false, 'Digital Marketing', '{}', 67),
       (73, false, false, 'Email Marketing', '{}', 67),
       (74, false, false, 'Lead Generation', '{}', 67),
       (75, false, false, 'Market Research', '{}', 67),
       (76, false, false, 'Marketing Automation', '{}', 67),
       (77, false, false, 'Marketing Strategy', '{}', 67),
       (78, false, false, 'Public relations', '{}', 67),
       (79, false, false, 'Sales & Business Development', '{}', 67),
       (80, false, false, 'Search Engine Marketing', '{}', 67),
       (81, false, false, 'Search Engine Optimisation', '{}', 67),
       (82, false, false, 'Social Media Marketing', '{}', 67),
       (83, false, false, 'Social Media Strategy', '{}', 67),
       (84, false, false, 'Telemarketing', '{}', 67),
       (85, true, false, 'Product, User Experience & Research', '{}', NULL),
       (86, true, true, 'Business Analysis', '{}', 85),
       (87, true, true, 'Graphic Design', '{}', 85),
       (88, false, false, 'Illustration', '{}', 85),
       (89, false, false, 'Initiative Management', '{}', 85),
       (90, false, false, 'Logo Design', '{}', 85),
       (91, true, true, 'Product Management', '{}', 85),
       (92, true, true, 'UI Mockups', '{"tools": ["figma"]}', 85),
       (93, true, true, 'User Research', '{"activities": ["interviews"]}', 85),
       (94, true, true, 'UX/UI Design', '{"tools": ["figma", "adobe xd", "invision"], "design-systems": ["ant-design", "material-design"]}', 85),
       (95, true, false, 'Software Development (inc. Web, Mobile)', '{}', NULL),
       (96, false, false, 'AR/VR Development', '{}', 95),
       (97, true, true, 'Backend Development', '{"python ecosystem": ["django", "flask"], "java ecosystem": ["java", "spring-boot"], "languages": ["golang", "python", "java"]}', 95),
       (98, false, false, 'Blockchain Development', '{}', 95),
       (99, false, false, 'CMS Development', '{}', 95),
       (100, false, false, 'Database Development', '{}', 95),
       (101, false, false, 'Desktop Software Development', '{}', 95),
       (102, false, false, 'E-commerce Development', '{}', 95),
       (103, false, false, 'Emerging Tech', '{}', 95),
       (104, false, false, 'Firmware Development', '{}', 95),
       (105, true, true, 'Frontend Development', '{"libraries": ["react", "redux", "vue"], "languages": ["javascript", "typescript"], "technologies": ["graphql", "rest"]}', 95),
       (106, true, true, 'Full-stack Development', '{"frameworks": ["django"]}', 95),
       (107, false, false, 'Game Development', '{}', 95),
       (108, false, false, 'Manual Testing', '{}', 95),
       (109, false, false, 'Mobile App Development', '{}', 95),
       (110, false, false, 'Mobile Design', '{}', 95),
       (111, false, false, 'Mobile Game Development', '{}', 95),
       (112, false, false, 'Prototyping', '{}', 95),
       (113, false, false, 'Scripting & Automation', '{}', 95),
       (114, true, true, 'Test Automation', '{"frameworks": ["cypress"]}', 95),
       (115, false, false, 'Web Design', '{}', 95),
       (116, false, false, 'Translation', '{}', NULL),
       (117, false, false, 'General Language Translation', '{}', 116),
       (118, false, false, 'Language Localisation', '{}', 116),
       (119, false, false, 'Language Tutoring', '{}', 116),
       (120, false, false, 'Legal Translation', '{}', 116),
       (121, false, false, 'Technical Translation', '{}', 116),
       (122, false, false, 'Business Writing', '{}', 116),
       (123, false, false, 'Writing', '{}', NULL),
       (124, false, false, 'Content Writing', '{}', 123),
       (125, false, false, 'Copywriting', '{}', 123),
       (126, false, false, 'Creative Writing', '{}', 123),
       (127, false, false, 'Editing & Proofreading', '{}', 123),
       (128, false, false, 'Ghostwriting', '{}', 123),
       (129, false, false, 'Grant Writing', '{}', 123),
       (130, false, false, 'Scriptwriting', '{}', 123),
       (131, false, false, 'Technical Writing', '{}', 123);