# Generated by Django 3.1 on 2021-04-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_contributorguide'),
        ('work', '0081_auto_20210427_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contribution_guide',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='license.contributorguide'),
        ),
    ]
